pr 요청 _ 하림
cleancode-practice-study/java-practice-blackjack pull request #1
Opened 2022-03-13 18:53 UTC by gkfla668

이번 구현.. 굉장히 복잡쓰하네요.. if-else문이랑 indent 2개이상 필요한 부분이 많은데
최대한 안쓰려고하니까 메소드가 잘게 쪼개지긴하지만 그만큼 미친듯이 머리가..... ㅎㅎㅎ 🥵

아직 else문도 있고 indent 2개이상인 부분도 최~~대한 생각해 보았지만 답이 안나와서 ..
무승부도 추가되면서 경우가 3가지라서 코드가 더 복잡해졌어요 흐구

많이 부족한 엉망진창 코드쥐만 ... 중간 피드백을 받고자 이 쯤에서 pr요청합니다!
바쁘신데 감사해요~~🙇‍♀️🙇‍♀️🙇‍♀️

2022-03-27 13:57 UTC, gch01410 requested changes
늦게 리뷰해서 미안 😢 
구현하기 쉽지않았을텐데 고생 많았어!

2022-03-27 13:57 UTC, ghost commented on src/main/java/controller/InputController.java
> +public class InputController {
InputController, PrintController를 만든 이유를 알 수 있을까?

2022-03-27 13:57 UTC, ghost commented on src/main/java/domain/Player.java
> +    public static Player createPlayer(String name) {
https://it-mesung.tistory.com/184 여기 내용 확인해봐!
메서드 이름도 적절하게 변경해보자!

2022-03-27 13:57 UTC, ghost commented on src/main/java/domain/RandomCard.java
> +        String[] numbers = {"2", "3", "4", "5", "6", "7", "8", "9", "A", "J", "K", "Q"};
Enum을 사용해서 shape, number를 관리해보자!

2022-03-27 13:57 UTC, gch01410 commented on src/main/java/domain/Player.java
> +    public List<String> cards;
인스턴스 변수는 반드시 private으로 선언해줘!!

2022-03-27 13:57 UTC, gch01410 commented on src/main/java/domain/Result.java
> +            if (Validator.isTenNumber(number)) {
Validator 객체는 입력 값에 대한 유효성 검증만을 해야하지않을까?
게임결과를 구할때 필요한 판단로직들은 어디에 있는게 좋을지 고민해봐!

2022-03-27 13:57 UTC, gch01410 commented on src/main/java/domain/Result.java
> +            Validator.checkUserTie(userWinOrLoseResult, dealer, user);
여기도 Validator에 있는게 맞는 로직들인지 고민해봐!

2022-03-27 13:57 UTC, gch01410 commented on src/main/java/domain/Result.java
> +        return new ArrayList<>(Arrays.asList(winCount, loseCount, tieCount));
리스트의 순서로 값을 구분하지않고 다른방법으로 값을 구분해볼 수 있을까?

2022-04-01 08:12 UTC, gkfla668 commented on src/main/java/controller/InputController.java
> +public class InputController {
아녀 다른 이유는 없고 ... controller가 메서드들을 너무 많이 담고있어서 그냥 분리해봤는데 그냥 한곳에 다 놓는게 나을까요?!?!

2022-04-01 08:12 UTC, gkfla668 commented on src/main/java/domain/Player.java
> +    public static Player createPlayer(String name) {
뭘 수정해야할지 잘 이해가 안가서 ㅠㅠ 이름 수정만 해보았습니다..

2022-04-04 15:48 UTC, gch01410 requested changes
Enum 사용 👍 👍 
전체적으로 static 메서드가 과하게 사용되고 있어
한번 수정해보자!

2022-04-04 15:48 UTC, gch01410 commented on src/main/java/controller/InputController.java
> +public class InputController {
컨트롤러끼리 호출을 하지는 않아서 컨트롤러는 하나만 두는게 좋아보여!

2022-04-04 15:48 UTC, gch01410 commented on src/main/java/domain/CardNumbers.java
> +    }
stream 사용하도록 변경해보자!

2022-04-04 15:48 UTC, gch01410 commented on src/main/java/domain/CardNumbers.java
> +    CardNumbers(int cardIdx, String cardNumber) {
생성자의 접근제어자가 default네
default로 한 이유가 있을까?

2022-04-04 15:48 UTC, gch01410 commented on src/main/java/domain/CardShapes.java
> +    스페이드(3, "스페이드");
보통 변수명으로 한글을 사용하지않고 영어만 사용해!
한글은 문자열만!

2022-04-04 15:48 UTC, gch01410 commented on src/main/java/domain/CardShapes.java
> +    }
여기도 stream사용하도록 바꿔보자!

2022-04-04 15:48 UTC, gch01410 commented on src/main/java/domain/Player.java
> +    public static List<String> getInitialCards() {
메서드명에 's' 붙인것 👍 
근데 이건 클래스내 다른 메서드에서만 호출되고 있어서 private 선언이 맞지않을까?

2022-04-04 15:48 UTC, gch01410 commented on src/main/java/domain/Player.java
> +        return users;
여기도 stream 사용하도록 변경해보자!
그리고 stream을 사용해서 구현했을때와 for 반복문으로 구현했을때 어떤것이 가독성이 좋은지 생각해봐!
둘 중 하나가 가독성이 더 좋다는게 아니고 그때 상황마다 항상 달라! 
그리고 지금 상황에서 stream이 가독성이 좋다는말도 아니고 그냥 한번 비교해봐!

2022-04-04 15:48 UTC, gch01410 commented on src/main/java/domain/CardNumbers.java
> +    private static int count = 0;
사용안하는 값은 삭제해줘!

2022-04-04 15:48 UTC, gch01410 commented on src/main/java/controller/PrintController.java
> +    }
Result의 static 메서드를 호출해서 결과를 만들지말고 Result객체 자체가 결과값을 갖고있도록 하는게 좋지않을까?
Result라는 클래스 이름상 그렇게해야 자연스러워보여!
지금은 게임결과를 생성해주는 보조적인 역할을 하고 있어서 ResultCreator 이런 느낌이 낫지않을까하네

2022-04-04 15:48 UTC, gch01410 commented on src/main/java/domain/Card.java
> +        return number + shape;
enum이 갖고있는 문자열을 이용하지않고 enum자체를 사용해도 되지않을까?

지금은 String으로 숫자,모양을 관리하고 있는데 enum인 CardNumber, CardShape 를 같이 관리하려면 어떻게 하면 좋을지도 고민해봐!

2022-04-04 15:48 UTC, gch01410 commented on src/main/java/domain/Player.java
> +    }
전에 클래스내에 메서드를 선언하는 순서가 있다고 했었어!
프로그램 전체적으로 다 적용해봐!

2022-04-04 15:48 UTC, gch01410 commented on src/main/java/domain/Player.java
> +    }
Player 객체를 생성하는 방법으로는 지금처럼 static 메서드에서 생성자를 호출하는 방법이 있고, 바로 생성자를 호출하는 방법이 있는데 지금 이 방법을 선택한 이유를 알 수 있을까?
static으로 안하고 충분히 구현할 수 있는 로직은 굳이 static을 사용안해도 돼!

2022-04-08 02:59 UTC, gkfla668 commented on src/main/java/domain/CardNumbers.java
> +    CardNumbers(int cardIdx, String cardNumber) {
private으로 하면 회색으로 떠서.. 필요없구나 하고 지웠었어요..!! 😯

2022-04-08 08:10 UTC, gkfla668 commented
최대한 피드백 반영해서 수정해봤는데 어렵네요 ..  ㅠㅠ 이렇게 하는게 맞나요 ?? . 
부족하지만 푸쉬합니당 .. 
아그리고 생성자 접근제어자가 다른곳에서 객체 생성하면서 호출해서 그런지 자동으로 설정된건데 
제가 잘못 구현한거 맞죠 ,, ㅎㅎ 
피드백 부탁드려요 ~ ! ! ! 😅

2022-04-09 06:32 UTC, ghost requested changes
거의 다 왔어
조금만 더 수정해봐!

2022-04-09 06:32 UTC, ghost commented on src/main/java/domain/Creator.java
> +        return names.stream().map(name -> new Player(name, Cards.getInitialCards())).collect(Collectors.toList());
```java
return names.stream()
    .map(name -> new Player(name, Cards.getInitialCards()))
    .collect(Collectors.toList());
```
`.` 마다 한줄씩 띄워주면 보기가 더 편해져!

2022-04-09 06:32 UTC, gch01410 commented on src/test/java/ConvertTest.java
> +                add(new Player("jinhee", Cards.create()));
테스트코드가 실패하고 있네!
확인해줘!

2022-04-09 06:32 UTC, ghost commented on src/main/java/controller/Controller.java
> +        Map<String, Integer> dealerResult = Creator.getDealerResult(participantsResult);
```java
GameResult participantsResult = GameResultCreator.getParticipantsResult(dealer, participants);
GameResult dealerResult = GameResultCreator.getDealerResult(participantsResult);
```
이런 느낌으로 만들면 어떨까?
GameResult 객체는 게임결과만을 갖고 있고, 다른 객체가 GameResult를 생성하도록!

2022-04-09 14:13 UTC, merged