pr 요청_진희
cleancode-practice-study/java-practice-blackjack pull request #2
Opened 2022-03-14 02:00 UTC by Egenieee

아직 리팩토링 할 곳이 많이 보이기는 한데,, 손을 어디서부터 대야할 지 잘 모르겠어서 일단은 로직 구현만 다 한뒤에 pr 요청합니다..!

* 일급컬렉션 사용하기 : card(String)를 모아놓은 List 컬렉션, 승부 결과를 담을 Map 컬렉션 -> 일급컬렉션으로 만들기
* Controller 역할 줄이기

이 두 가지는 리팩토링해야 할 걸로 보이는데 어떻게 리팩토링 하면 좋을지,, ㅠ 지금막 코드들이 꼬인게 잘 안풀어져서 **help** 요청 합니다,, 🙏

항상 바쁘신 데 신경써주셔서 감사합니다 따흑,,!

2022-03-27 11:48 UTC, gch01410 requested changes
엄청 늦어서 미안 ㅜㅜ
천천히 리팩토링해보자!

2022-03-27 11:48 UTC, gch01410 commented on src/main/java/model/Participant.java
> +    private final String name;
추상클래스를 하나 만들고 딜러와 참가자가 추상클래스를 상속받도록 변경해볼 수 있을까?

2022-03-27 11:48 UTC, gch01410 commented on src/main/java/model/RandomCardCreator.java
> +        StringBuilder stringBuilder = new StringBuilder();
StringBuilder를 사용한 이유를 알 수 있을까?

2022-03-27 11:48 UTC, gch01410 commented on src/main/java/model/BlackJackGame.java
> +        return String.join(", ", participantNames);
노출에 관한 로직은 View영역에서 처리해야해!

2022-03-27 11:48 UTC, gch01410 commented on src/main/java/controller/Controller.java
> +        getFinalCardState(participants, dealer);
이름이 get으로 시작하는 메서드는 반환값이 있을것으로 기대하는데 반환값이 없네 ㅜ
메서드에서 처리하는 로직에 맞도록 적절하게 이름을 변경해보자

2022-03-27 11:48 UTC, gch01410 commented on src/main/java/controller/Controller.java
> +            isAdded = InputView.getAdditionCard(participant.getName());
https://tecoble.techcourse.co.kr/post/2020-04-26-Method-Naming/ 참고해서 반환타입에 맞게 메서드이름을 변경해보자!

2022-03-27 11:48 UTC, gch01410 commented on src/main/java/model/BlackJackGame.java
> +        int participantResult = STANDARD_NUMBER - participant.getCardSum();
Participant 객체가 Card정보를 갖고 있으니 dealerResult를 Participant로 넘기면 Participant객체가 결과를 구할 수 있지않을까?

2022-03-27 11:48 UTC, gch01410 commented on src/main/java/model/Participant.java
> +    private final Map<String, Integer> gameResult = new HashMap<>();
딜러와 참가자가 게임결과를 반드시 갖고 있어야하는지 고민해봐!

2022-03-27 11:48 UTC, gch01410 commented on src/main/java/model/RandomCardCreator.java
> +    private static final List<String> cardTypes = Arrays.asList("스페이드", "하트", "클로버", "다이아몬드");
CardNumber, CardType을 enum으로 관리해보자!

2022-03-30 16:00 UTC, gch01410 requested changes
피드백 반영 잘했어! 👍 
조금만 더 리팩토링해보자!

2022-03-30 16:00 UTC, ghost commented on src/main/java/model/BlackJackGame.java
> +    private static final String DRAW = "무";
서로 관련있는 상수들을 enum으로 만들어서 관리하면 다루기가 편해져!

2022-03-30 16:00 UTC, ghost commented on src/main/java/model/Player.java
> +public abstract class Player {
추상클래스는 추상메서드를 가질 수 있어!
추상메서드가 어떤건지 알아보고 적용해볼 수 있는지 확인해봐!

2022-03-30 16:00 UTC, ghost commented on src/main/java/model/BlackJackGame.java
> +        return participants;
깔끔하게 잘 했어!
Straeam 사용해서 한번 구현해봐!

2022-03-30 16:00 UTC, ghost commented on src/main/java/model/RandomCardCreator.java
> +public class RandomCardCreator {
RandomCardCreator.java 파일 하나에 enum과 클래스를 여러개 선언했는지 알 수 있을까?

2022-03-30 16:00 UTC, ghost commented on src/main/java/model/RandomCardCreator.java
> +        return card;
card 변수의 선언과 초기화를 따로한 이유를 알 수 있을까?
그리고 card정보를 String으로 선언해서 관리하지않고 객체를 만들어서 관리해보면 어떨까?

2022-03-30 16:00 UTC, ghost commented on src/main/java/model/BlackJackGame.java
> +        Map<String, String> participantGameResult = new HashMap<>();
일급컬렉션으로 생성할만한 값들이 많이 보이네!
일급컬렉션을 만들어서 컬렉션(map,list,set)을 사용하는 로직들을 일급컬렉션 안으로 집어 넣어봐!

2022-03-30 22:01 UTC, Egenieee commented on src/main/java/model/RandomCardCreator.java
> +public class RandomCardCreator {
따로 선언하는 것과 안에 함께 선언하는 것 중에는 따로 선언하는게 더 나은걸까요?

2022-04-04 04:18 UTC, Egenieee commented
일단 피드백 받은 거 위주로 수정하고 Test code까지 작성해서 푸쉬합니다!
지금 못한 부분이 **Stream 사용** 이랑 **abstract method 사용**인데, Stream은 구글링을 해봐도 문법을 잘 모르겠어서ㅠㅠ 도와주시면 감사하겠습니다.. abstract method는 이름이 같은 메서드를 참가와 딜러 객체에서 사용중이기는 한데, 매개 변수 타입이 달라서 일단 추상메서드는 사용 안하고 구현했습니다!

2022-04-06 15:24 UTC, ghost requested changes
테스트코드 완벽하네 💯 💯 
잘했어! 👍

2022-04-06 15:24 UTC, ghost commented on src/main/java/view/InputView.java
> +    private static final String INPUT_ADDITIONAL_CARD_ERROR_MESSAGE = "y 혹은 n로 입력해주세요.";
사용안하는 값은 삭제해줘

2022-04-06 15:24 UTC, ghost commented on src/main/java/controller/Controller.java
> +        } while (!names.contains(","));
여기 로직만 보면 반드시 에러메시지를 출력하는것처럼 보여!
메서드 이름을 입력값에 대한 검증한다는 의미로 짓는건 어때?

2022-04-06 15:24 UTC, ghost commented on src/main/java/domain/Card.java
> +    String card;
String으로 관리하지않고 enum을 직접 갖고 있는게 더 직관적이지 않을까?

2022-04-06 15:24 UTC, ghost commented on src/main/java/domain/Player.java
> +public abstract class Player {
abstract 클래스를 상속한 클래스들이 공동으로 갖는 메서드 중에 내부로직이 다른 메서드는 abstract 메서드로 만들 수 있어!
getGameResult 메서드를 abstract 메서드로 만들 수 있어보여!

2022-04-06 15:24 UTC, gch01410 commented on src/main/java/domain/Participants.java
> +        return names;
stream 사용해도록 변경해보자!

2022-04-06 15:24 UTC, gch01410 commented on src/main/java/domain/Dealer.java
> +        return Calculator.getCardSum(cards) <= 16;
상수로 선언해주면 의미를 더 잘 드러낼 수 있어!
다른사람은 16이라는 값이 어떤 의미를 가지는 숫자인지 모를 수 있으니깐

2022-04-06 15:24 UTC, gch01410 commented on src/main/java/domain/Calculator.java
> +        if ((sumOne >= 21 && sumEleven >= 21) && (Math.abs(CARD_STANDARD - sumOne) < Math.abs(CARD_STANDARD - sumEleven)) ) {
이 숫자값도 상수이어야 하지 않을까?

2022-04-06 15:24 UTC, gch01410 commented on src/main/java/domain/Participant.java
> +            return GameResultType.LOSE.getCardType();
enum을 그대로 반환해서 사용하는건 어때?

2022-04-06 15:24 UTC, gch01410 commented on src/main/java/controller/Controller.java
> +        CardState cardState;
변수 선언화 초기화를 따로 한 이유가 있을까?

2022-04-06 15:24 UTC, gch01410 commented on src/test/java/domain/BlackJackGameTest.java
> +        assertThat(participants.getParticipants().get(2).getName()).isEqualTo("진희");
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 오손도손 게임하는것 같네 😃

2022-04-06 23:39 UTC, Egenieee commented on src/test/java/domain/BlackJackGameTest.java
> +        assertThat(participants.getParticipants().get(2).getName()).isEqualTo("진희");
😆😆😆

2022-04-07 05:40 UTC, gch01410 commented
수고했어! 💯 💯

2022-04-07 05:40 UTC, merged